name: Nightly Release and GH Pages Workflow

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *'  # Runs at midnight UTC every day

jobs:
  build-and-release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@master
        with:
          submodules: true
          ref: 'develop'
          
      - name: Download last successful commit SHA artifact
        uses: actions/download-artifact@v4
        with:
          name: last-successful-commit
        continue-on-error: true # Ensure we continue the first time, where there is no artifact yet.
  
      - name: Check for changes since last successful build
        id: check-changes
        run: |
          if [ -f last-successful-commit.txt ]; then
            LAST_SUCCESSFUL_SHA=$(cat last-successful-commit.txt)
            CURRENT_SHA=$(git rev-parse HEAD)
            if [ "$LAST_SUCCESSFUL_SHA" = "$CURRENT_SHA" ]; then
              echo "No changes since the last build. Exiting."
              exit 78  # Neutral exit to stop workflow
            fi
          else
            echo "No previous build found, assuming first run."
          fi
          
      - name: Set up Python
        uses: actions/setup-python@master
        with:
          python-version: '3.10' # Specify the Python version.

      - name: Install Dependencies
        run: |
          sudo apt update
          sudo DEBIAN_FRONTEND=noninteractive apt-get install -y libreoffice
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run Make nightly
        run: make nightly

      - name: Read _VERSION file
        id: version
        run: echo "::set-output name=version::$(cat ./_VERSION)"
      
      - name: Update Release Tag in index.rst
        run: |
          sed -i "s|RELEASE_TAG_PLACEHOLDER|${{ steps.version.outputs.id }}|g" ./source/index.rst

      - name: Create and Upload Release Assets
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ steps.version.outputs.id }}  # Uses the tag name
          name: Nightly Build ${{ steps.version.outputs.id }}
          draft: true
          prerelease: false
          files: |
            ./dist/docx/nightly-DENT-OIP.docx
            ./dist/pdf/nightly-DENT-OIP.pdf
            ./dist/nightly-codes.csv
            ./dist/nightly-views.csv
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Publish HTML to gh-pages branch
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist/html/
          destination_dir: nightly

      - name: Store the current commit SHA for future checks
        run: echo "$(git rev-parse HEAD)" > last-successful-commit.txt
  
      - name: Upload current commit SHA as an artifact
        uses: actions/upload-artifact@v4
        with:
          name: last-successful-commit
          path: last-successful-commit.txt
  