name: Release

on:
  workflow_dispatch:
  push:
    branches:
      - master

jobs:
  build-and-release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          submodules: true
          ref: master
          
      - name: Get VERSION from VERSION file
        id: version
        run: |
          VERSION_FILE="./VERSION"
          if [ -f "$VERSION_FILE" ]; then
            echo "VERSION=$(cat $VERSION_FILE)" >> $GITHUB_ENV
            echo "VERSION=$(cat $VERSION_FILE)" >> $GITHUB_OUTPUT
          else
            echo "Cannot load VERSION from $VERSION_FILE"
            exit 1
          fi
      
      - name: Set up Python
        uses: actions/setup-python@master
        with:
          python-version: '3.10' # Specify the Python version.

      - name: Install Dependencies
        run: |
          sudo apt update
          sudo DEBIAN_FRONTEND=noninteractive apt-get install -y libreoffice
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Update Release Tag in index.rst
        run: |
          sed -i "s|RELEASE_TAG_PLACEHOLDER|v${{ steps.version.outputs.VERSION }}|g" ./source/index.rst

      - name: Run Make dist
        run: make dist

      - name: Create and Upload Release Assets
        uses: softprops/action-gh-release@v2
        with:
          tag_name: v${{ steps.version.outputs.VERSION }}  # Uses the tag name
          name: Release v${{ steps.version.outputs.VERSION }}
          draft: false
          prerelease: true
          files: |
            ./dist/docx/DENT-OIP.docx
            ./dist/pdf/DENT-OIP.pdf
            ./source/tables/codes.csv
            ./source/tables/views.csv
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Publish HTML to gh-pages branch
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist/html/
          destination_dir: release

      - name: Update Latest Tag
        run: |
          git tag -d latest || true  # Delete the local tag if it exists
          git push origin :refs/tags/latest || true  # Delete the remote tag if it exists
          git tag -a latest -m "Updated latest tag"
          git push origin latest
