name: Release Workflow

on:
  workflow_dispatch:
  push:
    tags:
      - 'v*'

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Create and Upload Release Assets
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ github.ref_name }}  # Uses the tag name
          name: Release ${{ github.ref_name }}
          draft: false
          prerelease: false
          files: |
            ./source/tables/codes.csv
            ./source/tables/views.csv
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
